import json, io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
p = json.load(open('plan.json', encoding='utf-8'))
S = {}
S['W1-01'] = {"setup": "Desk, phone, Lane A. Outfit 1.", "order": 1, "words": 94, "seconds": 35,
"spoken": "Banks are cutting rates two weeks before the RBA might raise them.\n\nRead that again.\n\nDozens of lenders have cut variable rates in the past month. For new customers.\n\nAt the same time, markets are pricing about an 80 per cent chance the Reserve Bank lifts the cash rate on the 29th.\n\nBoth can be true. Banks are fighting over a shrinking pool of borrowers, so the discount goes to whoever walks in the door.\n\nIf you've been with your bank more than a year and haven't asked, you're funding that discount.\n\nAsk before the 29th. It's a phone call.",
"onScreen": "Cutting for new customers. Raising for everyone.", "numbers": "\"80%\" at the pricing line. \"29 Sept\" at the close.",
"disclaimerText": "This is a scenario, not a forecast. General market commentary only, not advice.",
"caption": "Banks are cutting rates two weeks before the RBA might raise them.\n\nDozens of lenders cut variable rates in the past month. For new customers. Meanwhile markets price about an 80% chance of a cash rate rise on 29 September.\n\nBoth are true. Banks are fighting over fewer borrowers, so the discount goes to whoever asks.\n\nIf you haven't asked in a year, you're funding it.\n\nSave this for the day after the 29th.\n\nThis is a scenario, not a forecast. General market commentary only, not advice. [credit rep line]\n\n#mortgagebroker #rba #interestrates #australianproperty #sydneyproperty #homeloans"}
S['W1-06'] = {"setup": "Desk, phone, Lane A. Outfit 1.", "order": 2, "words": 93, "seconds": 35,
"spoken": "Fixing your rate is buying insurance from the person who sets the price.\n\nOver a full cycle, variable has beaten fixed almost every time. The bank prices the fixed rate, and the bank is not in the business of losing that bet.\n\nRight now the best fixed rates sit above the best variable ones. So fixing today isn't a discount. It's a hedge.\n\nAnd a hedge is fine, if you know that's what you're buying.\n\nWho it's right for: the borrower who genuinely couldn't hold another rise.\n\nCertainty has a price. Just know you're paying it.",
"onScreen": "Certainty has a price.", "numbers": "None. No rate numbers anywhere, above and below only.",
"disclaimerText": "This is a scenario, not a forecast. General market commentary only, not advice.",
"caption": "Fixing your rate is buying insurance from the person who sets the price.\n\nOver a full cycle, variable has beaten fixed almost every time. The bank sets the fixed price and it doesn't plan to lose.\n\nRight now fixed sits above variable, so fixing is a hedge, not a discount.\n\nWho it suits: the borrower who genuinely couldn't hold another rise. Certainty has a price. Know you're paying it.\n\nThis is a scenario, not a forecast. General market commentary only, not advice. [credit rep line]\n\n#fixedrate #mortgagebroker #homeloans #interestrates #australianproperty"}
S['W1-08'] = {"setup": "Desk, phone, Lane A. Outfit 2 (shirt change). The car works too, parked, engine off.", "order": 3, "words": 99, "seconds": 38,
"spoken": "Your HECS debt is costing you more borrowing power than your car loan.\n\nA client asked this week whether a forty thousand dollar balance mattered. It matters more than the number suggests.\n\nLenders don't look at what you owe. They look at the repayment coming out of your pay, and they treat it like a loan you can't cancel.\n\nOn a typical calculator, that's six figures off what you can borrow.\n\nTwo things changed this year. Some lenders can now ignore a balance you'll clear within about a year. And paying it out of your deposit can leave you short on deposit.\n\nIt's a trade, not a rule.",
"onScreen": "Balance $40k. Capacity gone: six figures.", "numbers": "\"$40,000\" at the balance line. \"Six figures\" at the calculator line.",
"disclaimerText": "Illustrative only, not a quote or an offer. General market commentary, not advice.",
"caption": "Your HECS debt is costing you more borrowing power than your car loan.\n\nLenders don't assess the balance. They assess the compulsory repayment leaving your pay each month, and treat it like a loan you can't cancel. On a typical calculator a $40k balance takes six figures off your capacity.\n\nTwo things changed this year:\n→ some lenders can ignore a balance you'll clear within about a year\n→ paying it out of your deposit can leave you short on deposit\n\nIt's a trade, not a rule. Comment HECS and I'll do the long version.\n\nIllustrative only, not a quote or an offer. General market commentary, not advice. [credit rep line]\n\n#hecs #firsthomebuyer #borrowingpower #mortgagebroker #homeloans"}
S['W1-03'] = {"setup": "Desk plus a second angle 30 to 40 degrees off, Lane B. Outfit 2. Clap at the top of each take, cut to B on every point.", "order": 4, "words": 214, "seconds": 80,
"spoken": "The bank's favourite loan structure is the one that costs you the most.\n\nIt's called cross-collateralisation, and most people who have it don't know they have it.\n\nHere's how it happens. You own your home. You buy an investment property. The bank offers to lend against both together. One facility, one application, less paperwork. Sounds helpful.\n\nNow here's what you actually signed.\n\nEvery property secures every loan. The bank has a claim over the lot.\n\nSell one, and the bank revalues everything before it lets go. If values have dipped, it can hold your sale proceeds to fix up the loan on the one you kept.\n\nWant to refinance one property to a better lender? You can't. They come as a set.\n\nAnd every valuation, every top-up, runs through one credit team's view of your whole position.\n\nThe alternative is ring-fencing. Each property, its own loan. Use equity from one as a cash deposit on the next, but keep the securities separate.\n\nThe trade-off is real. More paperwork, sometimes two sets of fees, and it takes a broker willing to do the work instead of ticking the bank's box.\n\nBut you keep your options. And over ten years, options are worth more than convenience.",
"onScreen": "One loan, two houses. Guess who benefits. Then each point as text as you say it.", "numbers": "None. The four points appear as text on each turn.",
"disclaimerText": "General market commentary only, not advice.",
"caption": "The bank's favourite loan structure is the one that costs you the most.\n\nCross-collateralisation. One facility over your home and your investment. Less paperwork, and here's what you signed:\n\n→ every property secures every loan\n→ sell one and the bank revalues the lot first, and can hold your proceeds\n→ refinance one to a better lender? They come as a set\n→ every valuation runs through one credit team's view of everything\n\nThe alternative is ring-fencing. Each property, its own loan. Equity from one becomes a cash deposit on the next.\n\nThe trade-off: more paperwork, sometimes two sets of fees, and a broker willing to do the work.\n\nOver ten years, options beat convenience. Save this before your next purchase.\n\nGeneral market commentary only, not advice. [credit rep line]\n\n#propertyinvestor #loanstructure #mortgagebroker #australianproperty #investmentproperty"}
S['W1-02'] = {"setup": "Carousel, build from the copy. Navy, sky headings, white body, 1080x1350. Do not name the lenders.", "order": 5,
"slides": [["Cover", "Seven lenders cut investor borrowing power by up to 20%. Nobody sent you a letter."],
["What changed", "In the May Budget the government said rental losses on established property bought after 12 May 2026 stop offsetting your wages from 1 July 2027. New builds are exempt."],
["Why your bank cares", "For years lenders added the tax benefit of a rental loss back into your income when they assessed you. If the concession is going, so is the add-back."],
["Three columns", "Before: tax saving added back to income · Now: assessed on the cash shortfall alone · Result: up to 20% less borrowing on some calculators"],
["Who feels it", "The nine in ten investors with one or two properties, buying the next one this spring. Same job, same rent, smaller number."],
["The trade-off", "The new number is more honest. It's what the property actually costs you each month. Not a bad thing to know before you bid."],
["Close", "Get your capacity re-run before you bid. / Not after. A pre-approval from May might not be a pre-approval today."]],
"disclaimerText": "Anything to do with tax or structuring is your accountant's call, not mine. Illustrative only, not a quote or an offer.",
"caption": "Seven lenders cut investor borrowing power by up to 20%. Nobody sent you a letter.\n\nSince the Budget quarantined rental losses on established property bought after 12 May 2026 (from 1 July 2027), lenders have started removing the negative gearing add-back from how they assess investors.\n\nSame income. Same rent. Smaller number.\n\nThe new number is more honest, it's what the property actually costs you each month. But if you're bidding this spring on a pre-approval from May, get it re-run first.\n\nSend this to anyone bidding on an investment property this spring.\n\nAnything to do with tax or structuring is your accountant's call, not mine. Illustrative only, not a quote or an offer. General market commentary, not advice. [credit rep line]\n\n#negativegearing #propertyinvestor #borrowingpower #mortgagebroker #australianproperty"}
S['W1-04'] = {"setup": "Carousel, build from the copy.", "order": 6,
"slides": [["Cover", "742 followers. I'm taking this account to 10,000 in a year, and you get to watch."],
["Where I'm starting", "742 followers on 14 September 2026. A broker's account that posts when it remembers to."],
["The goal", "10,000 by 14 September 2027. That's about 178 new followers a week, every week."],
["The system", "→ 4 reels and 4 carousels a week → one filming day, Wednesday → a story every day → a Sunday review with real numbers"],
["What you'll get", "The read on rates and prices nobody else is running. How lenders actually assess you. Structure over rate. The positions most brokers won't say on camera."],
["What you won't get", "Client details. Rate quotes. Advice dressed up as content. A post that reads like a bank wrote it."],
["Hold me to it", "Every Sunday I'll post the numbers. Posts planned, posts published, followers gained. Misses included."],
["Close", "Follow to watch it happen. / Or watch it fail. Either way you'll see the numbers."]],
"disclaimerText": "General market commentary only, not advice.",
"caption": "742 followers. I'm taking this account to 10,000 in a year, in public.\n\nThe system: 4 reels and 4 carousels a week, one filming day, a story every day, and a Sunday review where I post the real numbers. Planned, published, followers gained. Misses included.\n\nWhat you'll get: the read on rates and prices nobody else is running, how lenders actually assess you, and the positions most brokers won't say on camera.\n\nWhat you won't get: client details, rate quotes, or advice dressed up as content.\n\nFollow to watch it happen, or watch it fail.\n\nGeneral market commentary only, not advice. [credit rep line]\n\n#mortgagebroker #buildinpublic #sydneybroker #australianproperty #loanmarket"}
S['W1-05'] = {"setup": "Carousel, build from the copy. Source credits: ATO taxation statistics. ABS Lending Indicators, June quarter 2026.", "order": 7,
"slides": [["Cover", "Nine in ten property investors own one or two places. The greedy landlord is mostly fiction."],
["The ATO's own numbers (three columns)", "71% own one property · 19% own two · About 1% own six or more"],
["Who they are", "Nurses, tradies, teachers, small business owners. Mostly on ordinary incomes, mostly building a retirement they don't trust the government to fund."],
["What's happening now", "Investor loan numbers fell 8.6% in the June quarter. Annual growth went from 19.4% to 2.8%. The investors are leaving, not hoarding."],
["The trade-off", "Some investors do hoard. Some suburbs have been priced by investors. And negative gearing is a concession, not a plan."],
["The real problem", "1.2 million homes promised. Delivery is now 18 months late. You can't tax your way to a house that hasn't been built."],
["Close", "Blame the supply. / Not the nurse with one unit in Penrith."]],
"disclaimerText": "General market commentary only, not advice. Anything to do with tax or structuring is your accountant's call, not mine.",
"caption": "Nine in ten property investors own one or two places. The greedy landlord is mostly fiction.\n\nATO data: 71% of investors own one property, 19% own two. About 1% own six or more.\n\nAnd they're leaving. Investor loan numbers fell 8.6% in the June quarter. Annual growth collapsed from 19.4% to 2.8%.\n\nSome investors do hoard. Some suburbs have been priced by them. But the housing problem is 1.2 million homes promised and delivery running 18 months late.\n\nYou can't tax your way to a house that hasn't been built.\n\nShare this with someone who blames landlords.\n\nGeneral market commentary only, not advice. Anything to do with tax or structuring is your accountant's call, not mine. [credit rep line]\n\n#propertyinvestor #negativegearing #housingcrisis #australianproperty #mortgagebroker"}
S['W1-07'] = {"setup": "Carousel, build from the copy. Refresh the clearance rate with the 19 to 20 Sep weekend result before posting. Credits: Cotality Home Value Index, August 2026. Auction results, Cotality and Domain.", "order": 8,
"slides": [["Cover", "Sydney is 7.1% off its peak and the buyers who waited for the dip are still waiting."],
["National, August (three columns)", "Down 0.9% in the month · Fifth straight fall · 3.6% below the March peak"],
["Sydney", "Down 1.4% in August. 7.1% below the February peak. A faster correction than 2022 to 2023."],
["How wide it is", "93% of capital city suburbs fell over winter. In autumn it was 46%."],
["Auctions", "Sydney clearance 57.8% last weekend. Same weekend last year: 77.1%."],
["The catch", "Your borrowing capacity fell too. This year's rate rises, tested through a 3% buffer, took more out of your number than the market gave back. And nobody rings a bell at the bottom."],
["Close", "You said you'd buy in the dip. / This is what one looks like from the inside."]],
"disclaimerText": "Illustrative only, not a quote or an offer. General market commentary, not advice.",
"caption": "Sydney is 7.1% off its peak and the buyers who waited for the dip are still waiting.\n\nCotality, August:\n→ national values down 0.9%, the fifth straight monthly fall, 3.6% below the March peak\n→ Sydney down 1.4%, 7.1% below February\n→ 93% of capital city suburbs fell over winter, up from 46% in autumn\n→ Sydney clearance 57.8% last weekend against 77.1% a year ago\n\nThe catch: your borrowing capacity fell too, and nobody rings a bell at the bottom.\n\nSave this and read it again in March.\n\nIllustrative only, not a quote or an offer. General market commentary, not advice. [credit rep line]\n\n#sydneyproperty #propertymarket #firsthomebuyer #australianproperty #mortgagebroker"}
for s in p['slots']:
    if s['id'] in S:
        s['script'] = S[s['id']]
for w in p['weeks']:
    if w['id'] == 'W1':
        w['storyClips'] = ["Tripod and phone from behind, the shot list on the laptop screen", "The three shirts on the back of the door", "The clap at the top of a Lane B take", "Edit screen with captions going on", "Wide of the desk, coffee, window light", "Talking to camera, 8 seconds: \"Week one. Eight posts. Sunday I'll tell you how many actually went out.\""]
        w['filmingRules'] = "Two takes maximum. Say the hook twice at the top of every take, once flat and once with more energy. Start on the first word. Number on screen the moment you say it, held two seconds. Sentence case captions, Poppins Bold, white with sky emphasis. Disclaimer muted grey in the final three seconds. Credit rep line on every caption."
raw = json.dumps(p, ensure_ascii=False)
assert "—" not in raw
json.dump(p, open('plan.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2)
print('scripts attached:', sum(1 for s in p['slots'] if 'script' in s))
